import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  learnSidebar: [
    {
      type: "doc",
      id: "learn/overview",
      className: "overview",
      label: "Moxie Overview",
    },
    {
      type: "link",
      href: "https://build.moxie.xyz/the-moxie-protocol/moxie-protocol",
      label: "Protocol Concepts",
      className: "concepts",
    },
    {
      type: "doc",
      id: "learn/glossary",
      className: "references",
      label: "Glossary",
    },
    {
      type: "doc",
      id: "learn/contract-whitelisting",
      label: "Contract Whitelisting",
      className: "hidden",
      // className: "shield_check",
    },
  ],
  apisSidebar: [{ type: "autogenerated", dirName: "api" }],
  protocolApisSidebar: [{ type: "autogenerated", dirName: "api/protocol" }],
  auctionApisSidebar: [{ type: "autogenerated", dirName: "api/auction" }],
  vestingApisSidebar: [{ type: "autogenerated", dirName: "api/vesting" }],
  offchainRestSidebar: [
    { type: "autogenerated", dirName: "api/clearing-price-api" },
  ],
  contractsSidebar: [{ type: "autogenerated", dirName: "contract" }],
  fanTokenAuctionsUseCasesSidebar: [
    { type: "autogenerated", dirName: "use-cases/fan-token-auctions" },
  ],
  bidsCasesSidebar: [{ type: "autogenerated", dirName: "use-cases/bids" }],
  fanTokensCasesSidebar: [
    { type: "autogenerated", dirName: "use-cases/fan-tokens" },
  ],
  usersCasesSidebar: [{ type: "autogenerated", dirName: "use-cases/users" }],
  ordersCasesSidebar: [{ type: "autogenerated", dirName: "use-cases/orders" }],
  protocolCasesSidebar: [
    { type: "autogenerated", dirName: "use-cases/protocol" },
  ],
  vestingCasesSidebar: [
    { type: "autogenerated", dirName: "use-cases/vesting" },
  ],
  farcasterDataSidebar: [{ type: "autogenerated", dirName: "farcaster-data" }],
};

export default sidebars;
