import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  conceptsSidebar: [{ type: "autogenerated", dirName: "concept" }],
  apisSidebar: [{ type: "autogenerated", dirName: "api" }],
  protocolApisSidebar: [{ type: "autogenerated", dirName: "api/protocol" }],
  auctionApisSidebar: [{ type: "autogenerated", dirName: "api/auction" }],
  vestingApisSidebar: [{ type: "autogenerated", dirName: "api/vesting" }],
  offchainRestSidebar: [
    { type: "autogenerated", dirName: "api/clearing-price-api" },
  ],
  offchainGraphQLSidebar: [
    { type: "autogenerated", dirName: "api/airstack-graphql" },
  ],
  contractsSidebar: [{ type: "autogenerated", dirName: "contract" }],
};

export default sidebars;
